'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18051
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace LocationReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClientInfo", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClientInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private UserNameField As String
        
        Private PasswordField As String
        
        Private VersionField As String
        
        Private AccountNumberField As String
        
        Private AccountPinField As String
        
        Private AccountEntityField As String
        
        Private AccountCountryCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property UserName() As String
            Get
                Return Me.UserNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserNameField, value) <> true) Then
                    Me.UserNameField = value
                    Me.RaisePropertyChanged("UserName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Version() As String
            Get
                Return Me.VersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VersionField, value) <> true) Then
                    Me.VersionField = value
                    Me.RaisePropertyChanged("Version")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property AccountNumber() As String
            Get
                Return Me.AccountNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountNumberField, value) <> true) Then
                    Me.AccountNumberField = value
                    Me.RaisePropertyChanged("AccountNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property AccountPin() As String
            Get
                Return Me.AccountPinField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountPinField, value) <> true) Then
                    Me.AccountPinField = value
                    Me.RaisePropertyChanged("AccountPin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property AccountEntity() As String
            Get
                Return Me.AccountEntityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountEntityField, value) <> true) Then
                    Me.AccountEntityField = value
                    Me.RaisePropertyChanged("AccountEntity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property AccountCountryCode() As String
            Get
                Return Me.AccountCountryCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountCountryCodeField, value) <> true) Then
                    Me.AccountCountryCodeField = value
                    Me.RaisePropertyChanged("AccountCountryCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
        Public Property Source() As Integer
            Get
                Return Me.SourceField
            End Get
            Set
                If (Me.SourceField.Equals(value) <> true) Then
                    Me.SourceField = value
                    Me.RaisePropertyChanged("Source")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Transaction", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Transaction
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private Reference1Field As String
        
        Private Reference2Field As String
        
        Private Reference3Field As String
        
        Private Reference4Field As String
        
        Private Reference5Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Reference1() As String
            Get
                Return Me.Reference1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Reference1Field, value) <> true) Then
                    Me.Reference1Field = value
                    Me.RaisePropertyChanged("Reference1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Reference2() As String
            Get
                Return Me.Reference2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Reference2Field, value) <> true) Then
                    Me.Reference2Field = value
                    Me.RaisePropertyChanged("Reference2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Reference3() As String
            Get
                Return Me.Reference3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Reference3Field, value) <> true) Then
                    Me.Reference3Field = value
                    Me.RaisePropertyChanged("Reference3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Reference4() As String
            Get
                Return Me.Reference4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Reference4Field, value) <> true) Then
                    Me.Reference4Field = value
                    Me.RaisePropertyChanged("Reference4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Reference5() As String
            Get
                Return Me.Reference5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Reference5Field, value) <> true) Then
                    Me.Reference5Field = value
                    Me.RaisePropertyChanged("Reference5")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Address", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Address
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private Line1Field As String
        
        Private Line2Field As String
        
        Private Line3Field As String
        
        Private CityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateOrProvinceCodeField As String
        
        Private PostCodeField As String
        
        Private CountryCodeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Line1() As String
            Get
                Return Me.Line1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Line1Field, value) <> true) Then
                    Me.Line1Field = value
                    Me.RaisePropertyChanged("Line1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Line2() As String
            Get
                Return Me.Line2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Line2Field, value) <> true) Then
                    Me.Line2Field = value
                    Me.RaisePropertyChanged("Line2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Line3() As String
            Get
                Return Me.Line3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Line3Field, value) <> true) Then
                    Me.Line3Field = value
                    Me.RaisePropertyChanged("Line3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityField, value) <> true) Then
                    Me.CityField = value
                    Me.RaisePropertyChanged("City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property StateOrProvinceCode() As String
            Get
                Return Me.StateOrProvinceCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateOrProvinceCodeField, value) <> true) Then
                    Me.StateOrProvinceCodeField = value
                    Me.RaisePropertyChanged("StateOrProvinceCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property PostCode() As String
            Get
                Return Me.PostCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostCodeField, value) <> true) Then
                    Me.PostCodeField = value
                    Me.RaisePropertyChanged("PostCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property CountryCode() As String
            Get
                Return Me.CountryCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryCodeField, value) <> true) Then
                    Me.CountryCodeField = value
                    Me.RaisePropertyChanged("CountryCode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Notification", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Notification
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodeField As String
        
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Code() As String
            Get
                Return Me.CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodeField, value) <> true) Then
                    Me.CodeField = value
                    Me.RaisePropertyChanged("Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Country", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Country
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodeField As String
        
        Private NameField As String
        
        Private IsoCodeField As String
        
        Private StateRequiredField As Boolean
        
        Private PostCodeRequiredField As Boolean
        
        Private PostCodeRegexField() As String
        
        Private InternationalCallingNumberField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Code() As String
            Get
                Return Me.CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodeField, value) <> true) Then
                    Me.CodeField = value
                    Me.RaisePropertyChanged("Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property IsoCode() As String
            Get
                Return Me.IsoCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IsoCodeField, value) <> true) Then
                    Me.IsoCodeField = value
                    Me.RaisePropertyChanged("IsoCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property StateRequired() As Boolean
            Get
                Return Me.StateRequiredField
            End Get
            Set
                If (Me.StateRequiredField.Equals(value) <> true) Then
                    Me.StateRequiredField = value
                    Me.RaisePropertyChanged("StateRequired")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property PostCodeRequired() As Boolean
            Get
                Return Me.PostCodeRequiredField
            End Get
            Set
                If (Me.PostCodeRequiredField.Equals(value) <> true) Then
                    Me.PostCodeRequiredField = value
                    Me.RaisePropertyChanged("PostCodeRequired")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property PostCodeRegex() As String()
            Get
                Return Me.PostCodeRegexField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostCodeRegexField, value) <> true) Then
                    Me.PostCodeRegexField = value
                    Me.RaisePropertyChanged("PostCodeRegex")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property InternationalCallingNumber() As String
            Get
                Return Me.InternationalCallingNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InternationalCallingNumberField, value) <> true) Then
                    Me.InternationalCallingNumberField = value
                    Me.RaisePropertyChanged("InternationalCallingNumber")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Office", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Office
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private EntityField As String
        
        Private EntityDescriptionField As String
        
        Private OfficeTypeField As String
        
        Private AddressField As LocationReference.Address
        
        Private TelephoneField As String
        
        Private WorkingDaysField As String
        
        Private WorkingHoursField As String
        
        Private LongtitudeField As Decimal
        
        Private LatitudeField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Entity() As String
            Get
                Return Me.EntityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EntityField, value) <> true) Then
                    Me.EntityField = value
                    Me.RaisePropertyChanged("Entity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property EntityDescription() As String
            Get
                Return Me.EntityDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EntityDescriptionField, value) <> true) Then
                    Me.EntityDescriptionField = value
                    Me.RaisePropertyChanged("EntityDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property OfficeType() As String
            Get
                Return Me.OfficeTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OfficeTypeField, value) <> true) Then
                    Me.OfficeTypeField = value
                    Me.RaisePropertyChanged("OfficeType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Address() As LocationReference.Address
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property Telephone() As String
            Get
                Return Me.TelephoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelephoneField, value) <> true) Then
                    Me.TelephoneField = value
                    Me.RaisePropertyChanged("Telephone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property WorkingDays() As String
            Get
                Return Me.WorkingDaysField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WorkingDaysField, value) <> true) Then
                    Me.WorkingDaysField = value
                    Me.RaisePropertyChanged("WorkingDays")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property WorkingHours() As String
            Get
                Return Me.WorkingHoursField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WorkingHoursField, value) <> true) Then
                    Me.WorkingHoursField = value
                    Me.RaisePropertyChanged("WorkingHours")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property Longtitude() As Decimal
            Get
                Return Me.LongtitudeField
            End Get
            Set
                If (Me.LongtitudeField.Equals(value) <> true) Then
                    Me.LongtitudeField = value
                    Me.RaisePropertyChanged("Longtitude")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Public Property Latitude() As Decimal
            Get
                Return Me.LatitudeField
            End Get
            Set
                If (Me.LatitudeField.Equals(value) <> true) Then
                    Me.LatitudeField = value
                    Me.RaisePropertyChanged("Latitude")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", ConfigurationName:="LocationReference.Service_1_0")>  _
    Public Interface Service_1_0
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ValidateAddress", ReplyAction:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ValidateAddressResponse")>  _
        Function ValidateAddress(ByVal request As LocationReference.AddressValidationRequest) As LocationReference.AddressValidationResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountries", ReplyAction:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountriesResponse")>  _
        Function FetchCountries(ByVal request As LocationReference.CountriesFetchingRequest) As LocationReference.CountriesFetchingResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountry", ReplyAction:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountryResponse")>  _
        Function FetchCountry(ByVal request As LocationReference.CountryFetchingRequest) As LocationReference.CountryFetchingResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCities", ReplyAction:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCitiesResponse")>  _
        Function FetchCities(ByVal request As LocationReference.CitiesFetchingRequest) As LocationReference.CitiesFetchingResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchOffices", ReplyAction:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchOfficesResponse")>  _
        Function FetchOffices(ByVal request As LocationReference.OfficesFetchingRequest) As LocationReference.OfficesFetchingResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="AddressValidationRequest", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class AddressValidationRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public ClientInfo As LocationReference.ClientInfo
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Transaction As LocationReference.Transaction
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=2)>  _
        Public Address As LocationReference.Address
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClientInfo As LocationReference.ClientInfo, ByVal Transaction As LocationReference.Transaction, ByVal Address As LocationReference.Address)
            MyBase.New
            Me.ClientInfo = ClientInfo
            Me.Transaction = Transaction
            Me.Address = Address
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="AddressValidationResponse", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class AddressValidationResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public Transaction As LocationReference.Transaction
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Notifications() As LocationReference.Notification
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=2)>  _
        Public HasErrors As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=3)>  _
        Public SuggestedAddresses() As LocationReference.Address
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Transaction As LocationReference.Transaction, ByVal Notifications() As LocationReference.Notification, ByVal HasErrors As Boolean, ByVal SuggestedAddresses() As LocationReference.Address)
            MyBase.New
            Me.Transaction = Transaction
            Me.Notifications = Notifications
            Me.HasErrors = HasErrors
            Me.SuggestedAddresses = SuggestedAddresses
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CountriesFetchingRequest", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class CountriesFetchingRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public ClientInfo As LocationReference.ClientInfo
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Transaction As LocationReference.Transaction
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClientInfo As LocationReference.ClientInfo, ByVal Transaction As LocationReference.Transaction)
            MyBase.New
            Me.ClientInfo = ClientInfo
            Me.Transaction = Transaction
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CountriesFetchingResponse", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class CountriesFetchingResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public Transaction As LocationReference.Transaction
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Notifications() As LocationReference.Notification
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=2)>  _
        Public HasErrors As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=3)>  _
        Public Countries() As LocationReference.Country
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Transaction As LocationReference.Transaction, ByVal Notifications() As LocationReference.Notification, ByVal HasErrors As Boolean, ByVal Countries() As LocationReference.Country)
            MyBase.New
            Me.Transaction = Transaction
            Me.Notifications = Notifications
            Me.HasErrors = HasErrors
            Me.Countries = Countries
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CountryFetchingRequest", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class CountryFetchingRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public ClientInfo As LocationReference.ClientInfo
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Transaction As LocationReference.Transaction
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=2)>  _
        Public Code As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClientInfo As LocationReference.ClientInfo, ByVal Transaction As LocationReference.Transaction, ByVal Code As String)
            MyBase.New
            Me.ClientInfo = ClientInfo
            Me.Transaction = Transaction
            Me.Code = Code
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CountryFetchingResponse", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class CountryFetchingResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public Transaction As LocationReference.Transaction
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Notifications() As LocationReference.Notification
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=2)>  _
        Public HasErrors As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=3)>  _
        Public Country As LocationReference.Country
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Transaction As LocationReference.Transaction, ByVal Notifications() As LocationReference.Notification, ByVal HasErrors As Boolean, ByVal Country As LocationReference.Country)
            MyBase.New
            Me.Transaction = Transaction
            Me.Notifications = Notifications
            Me.HasErrors = HasErrors
            Me.Country = Country
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CitiesFetchingRequest", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class CitiesFetchingRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public ClientInfo As LocationReference.ClientInfo
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Transaction As LocationReference.Transaction
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=2)>  _
        Public CountryCode As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=3)>  _
        Public State As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=4)>  _
        Public NameStartsWith As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClientInfo As LocationReference.ClientInfo, ByVal Transaction As LocationReference.Transaction, ByVal CountryCode As String, ByVal State As String, ByVal NameStartsWith As String)
            MyBase.New
            Me.ClientInfo = ClientInfo
            Me.Transaction = Transaction
            Me.CountryCode = CountryCode
            Me.State = State
            Me.NameStartsWith = NameStartsWith
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CitiesFetchingResponse", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class CitiesFetchingResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public Transaction As LocationReference.Transaction
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Notifications() As LocationReference.Notification
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=2)>  _
        Public HasErrors As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=3)>  _
        Public Cities() As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Transaction As LocationReference.Transaction, ByVal Notifications() As LocationReference.Notification, ByVal HasErrors As Boolean, ByVal Cities() As String)
            MyBase.New
            Me.Transaction = Transaction
            Me.Notifications = Notifications
            Me.HasErrors = HasErrors
            Me.Cities = Cities
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="OfficesFetchingRequest", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class OfficesFetchingRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public ClientInfo As LocationReference.ClientInfo
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Transaction As LocationReference.Transaction
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=2)>  _
        Public CountryCode As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClientInfo As LocationReference.ClientInfo, ByVal Transaction As LocationReference.Transaction, ByVal CountryCode As String)
            MyBase.New
            Me.ClientInfo = ClientInfo
            Me.Transaction = Transaction
            Me.CountryCode = CountryCode
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="OfficesFetchingResponse", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class OfficesFetchingResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public Transaction As LocationReference.Transaction
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Notifications() As LocationReference.Notification
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=2)>  _
        Public HasErrors As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=3)>  _
        Public Offices() As LocationReference.Office
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Transaction As LocationReference.Transaction, ByVal Notifications() As LocationReference.Notification, ByVal HasErrors As Boolean, ByVal Offices() As LocationReference.Office)
            MyBase.New
            Me.Transaction = Transaction
            Me.Notifications = Notifications
            Me.HasErrors = HasErrors
            Me.Offices = Offices
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Service_1_0Channel
        Inherits LocationReference.Service_1_0, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service_1_0Client
        Inherits System.ServiceModel.ClientBase(Of LocationReference.Service_1_0)
        Implements LocationReference.Service_1_0
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ValidateAddress(ByVal request As LocationReference.AddressValidationRequest) As LocationReference.AddressValidationResponse Implements LocationReference.Service_1_0.ValidateAddress
            Return MyBase.Channel.ValidateAddress(request)
        End Function
        
        Public Function FetchCountries(ByVal request As LocationReference.CountriesFetchingRequest) As LocationReference.CountriesFetchingResponse Implements LocationReference.Service_1_0.FetchCountries
            Return MyBase.Channel.FetchCountries(request)
        End Function
        
        Public Function FetchCountry(ByVal request As LocationReference.CountryFetchingRequest) As LocationReference.CountryFetchingResponse Implements LocationReference.Service_1_0.FetchCountry
            Return MyBase.Channel.FetchCountry(request)
        End Function
        
        Public Function FetchCities(ByVal request As LocationReference.CitiesFetchingRequest) As LocationReference.CitiesFetchingResponse Implements LocationReference.Service_1_0.FetchCities
            Return MyBase.Channel.FetchCities(request)
        End Function
        
        Public Function FetchOffices(ByVal request As LocationReference.OfficesFetchingRequest) As LocationReference.OfficesFetchingResponse Implements LocationReference.Service_1_0.FetchOffices
            Return MyBase.Channel.FetchOffices(request)
        End Function
    End Class
End Namespace
