'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace RateCalcService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClientInfo", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClientInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private UserNameField As String
        
        Private PasswordField As String
        
        Private VersionField As String
        
        Private AccountNumberField As String
        
        Private AccountPinField As String
        
        Private AccountEntityField As String
        
        Private AccountCountryCodeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property UserName() As String
            Get
                Return Me.UserNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserNameField, value) <> true) Then
                    Me.UserNameField = value
                    Me.RaisePropertyChanged("UserName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Version() As String
            Get
                Return Me.VersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VersionField, value) <> true) Then
                    Me.VersionField = value
                    Me.RaisePropertyChanged("Version")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property AccountNumber() As String
            Get
                Return Me.AccountNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountNumberField, value) <> true) Then
                    Me.AccountNumberField = value
                    Me.RaisePropertyChanged("AccountNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property AccountPin() As String
            Get
                Return Me.AccountPinField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountPinField, value) <> true) Then
                    Me.AccountPinField = value
                    Me.RaisePropertyChanged("AccountPin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property AccountEntity() As String
            Get
                Return Me.AccountEntityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountEntityField, value) <> true) Then
                    Me.AccountEntityField = value
                    Me.RaisePropertyChanged("AccountEntity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property AccountCountryCode() As String
            Get
                Return Me.AccountCountryCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountCountryCodeField, value) <> true) Then
                    Me.AccountCountryCodeField = value
                    Me.RaisePropertyChanged("AccountCountryCode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Transaction", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Transaction
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private Reference1Field As String
        
        Private Reference2Field As String
        
        Private Reference3Field As String
        
        Private Reference4Field As String
        
        Private Reference5Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Reference1() As String
            Get
                Return Me.Reference1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Reference1Field, value) <> true) Then
                    Me.Reference1Field = value
                    Me.RaisePropertyChanged("Reference1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Reference2() As String
            Get
                Return Me.Reference2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Reference2Field, value) <> true) Then
                    Me.Reference2Field = value
                    Me.RaisePropertyChanged("Reference2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Reference3() As String
            Get
                Return Me.Reference3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Reference3Field, value) <> true) Then
                    Me.Reference3Field = value
                    Me.RaisePropertyChanged("Reference3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Reference4() As String
            Get
                Return Me.Reference4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Reference4Field, value) <> true) Then
                    Me.Reference4Field = value
                    Me.RaisePropertyChanged("Reference4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Reference5() As String
            Get
                Return Me.Reference5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Reference5Field, value) <> true) Then
                    Me.Reference5Field = value
                    Me.RaisePropertyChanged("Reference5")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Address", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Address
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private Line1Field As String
        
        Private Line2Field As String
        
        Private Line3Field As String
        
        Private CityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateOrProvinceCodeField As String
        
        Private PostCodeField As String
        
        Private CountryCodeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Line1() As String
            Get
                Return Me.Line1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Line1Field, value) <> true) Then
                    Me.Line1Field = value
                    Me.RaisePropertyChanged("Line1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Line2() As String
            Get
                Return Me.Line2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Line2Field, value) <> true) Then
                    Me.Line2Field = value
                    Me.RaisePropertyChanged("Line2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Line3() As String
            Get
                Return Me.Line3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Line3Field, value) <> true) Then
                    Me.Line3Field = value
                    Me.RaisePropertyChanged("Line3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityField, value) <> true) Then
                    Me.CityField = value
                    Me.RaisePropertyChanged("City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property StateOrProvinceCode() As String
            Get
                Return Me.StateOrProvinceCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateOrProvinceCodeField, value) <> true) Then
                    Me.StateOrProvinceCodeField = value
                    Me.RaisePropertyChanged("StateOrProvinceCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property PostCode() As String
            Get
                Return Me.PostCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostCodeField, value) <> true) Then
                    Me.PostCodeField = value
                    Me.RaisePropertyChanged("PostCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property CountryCode() As String
            Get
                Return Me.CountryCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryCodeField, value) <> true) Then
                    Me.CountryCodeField = value
                    Me.RaisePropertyChanged("CountryCode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ShipmentDetails", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ShipmentDetails
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private DimensionsField As RateCalcService.Dimensions
        
        Private ActualWeightField As RateCalcService.Weight
        
        Private ChargeableWeightField As RateCalcService.Weight
        
        Private DescriptionOfGoodsField As String
        
        Private GoodsOriginCountryField As String
        
        Private NumberOfPiecesField As Integer
        
        Private ProductGroupField As String
        
        Private ProductTypeField As String
        
        Private PaymentTypeField As String
        
        Private PaymentOptionsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomsValueAmountField As RateCalcService.Money
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CashOnDeliveryAmountField As RateCalcService.Money
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InsuranceAmountField As RateCalcService.Money
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CashAdditionalAmountField As RateCalcService.Money
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CollectAmountField As RateCalcService.Money
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServicesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ItemsField() As RateCalcService.ShipmentItem
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Dimensions() As RateCalcService.Dimensions
            Get
                Return Me.DimensionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DimensionsField, value) <> true) Then
                    Me.DimensionsField = value
                    Me.RaisePropertyChanged("Dimensions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property ActualWeight() As RateCalcService.Weight
            Get
                Return Me.ActualWeightField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ActualWeightField, value) <> true) Then
                    Me.ActualWeightField = value
                    Me.RaisePropertyChanged("ActualWeight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property ChargeableWeight() As RateCalcService.Weight
            Get
                Return Me.ChargeableWeightField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ChargeableWeightField, value) <> true) Then
                    Me.ChargeableWeightField = value
                    Me.RaisePropertyChanged("ChargeableWeight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property DescriptionOfGoods() As String
            Get
                Return Me.DescriptionOfGoodsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionOfGoodsField, value) <> true) Then
                    Me.DescriptionOfGoodsField = value
                    Me.RaisePropertyChanged("DescriptionOfGoods")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property GoodsOriginCountry() As String
            Get
                Return Me.GoodsOriginCountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GoodsOriginCountryField, value) <> true) Then
                    Me.GoodsOriginCountryField = value
                    Me.RaisePropertyChanged("GoodsOriginCountry")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property NumberOfPieces() As Integer
            Get
                Return Me.NumberOfPiecesField
            End Get
            Set
                If (Me.NumberOfPiecesField.Equals(value) <> true) Then
                    Me.NumberOfPiecesField = value
                    Me.RaisePropertyChanged("NumberOfPieces")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property ProductGroup() As String
            Get
                Return Me.ProductGroupField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductGroupField, value) <> true) Then
                    Me.ProductGroupField = value
                    Me.RaisePropertyChanged("ProductGroup")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property ProductType() As String
            Get
                Return Me.ProductTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductTypeField, value) <> true) Then
                    Me.ProductTypeField = value
                    Me.RaisePropertyChanged("ProductType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Public Property PaymentType() As String
            Get
                Return Me.PaymentTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PaymentTypeField, value) <> true) Then
                    Me.PaymentTypeField = value
                    Me.RaisePropertyChanged("PaymentType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=9)>  _
        Public Property PaymentOptions() As String
            Get
                Return Me.PaymentOptionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PaymentOptionsField, value) <> true) Then
                    Me.PaymentOptionsField = value
                    Me.RaisePropertyChanged("PaymentOptions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=10)>  _
        Public Property CustomsValueAmount() As RateCalcService.Money
            Get
                Return Me.CustomsValueAmountField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomsValueAmountField, value) <> true) Then
                    Me.CustomsValueAmountField = value
                    Me.RaisePropertyChanged("CustomsValueAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=11)>  _
        Public Property CashOnDeliveryAmount() As RateCalcService.Money
            Get
                Return Me.CashOnDeliveryAmountField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CashOnDeliveryAmountField, value) <> true) Then
                    Me.CashOnDeliveryAmountField = value
                    Me.RaisePropertyChanged("CashOnDeliveryAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=12)>  _
        Public Property InsuranceAmount() As RateCalcService.Money
            Get
                Return Me.InsuranceAmountField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InsuranceAmountField, value) <> true) Then
                    Me.InsuranceAmountField = value
                    Me.RaisePropertyChanged("InsuranceAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=13)>  _
        Public Property CashAdditionalAmount() As RateCalcService.Money
            Get
                Return Me.CashAdditionalAmountField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CashAdditionalAmountField, value) <> true) Then
                    Me.CashAdditionalAmountField = value
                    Me.RaisePropertyChanged("CashAdditionalAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=14)>  _
        Public Property CollectAmount() As RateCalcService.Money
            Get
                Return Me.CollectAmountField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CollectAmountField, value) <> true) Then
                    Me.CollectAmountField = value
                    Me.RaisePropertyChanged("CollectAmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=15)>  _
        Public Property Services() As String
            Get
                Return Me.ServicesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServicesField, value) <> true) Then
                    Me.ServicesField = value
                    Me.RaisePropertyChanged("Services")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=16)>  _
        Public Property Items() As RateCalcService.ShipmentItem()
            Get
                Return Me.ItemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemsField, value) <> true) Then
                    Me.ItemsField = value
                    Me.RaisePropertyChanged("Items")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Dimensions", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Dimensions
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private LengthField As Integer
        
        Private WidthField As Integer
        
        Private HeightField As Integer
        
        Private UnitField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Length() As Integer
            Get
                Return Me.LengthField
            End Get
            Set
                If (Me.LengthField.Equals(value) <> true) Then
                    Me.LengthField = value
                    Me.RaisePropertyChanged("Length")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Width() As Integer
            Get
                Return Me.WidthField
            End Get
            Set
                If (Me.WidthField.Equals(value) <> true) Then
                    Me.WidthField = value
                    Me.RaisePropertyChanged("Width")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Height() As Integer
            Get
                Return Me.HeightField
            End Get
            Set
                If (Me.HeightField.Equals(value) <> true) Then
                    Me.HeightField = value
                    Me.RaisePropertyChanged("Height")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Unit() As String
            Get
                Return Me.UnitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UnitField, value) <> true) Then
                    Me.UnitField = value
                    Me.RaisePropertyChanged("Unit")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Weight", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Weight
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private UnitField As String
        
        Private ValueField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Unit() As String
            Get
                Return Me.UnitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UnitField, value) <> true) Then
                    Me.UnitField = value
                    Me.RaisePropertyChanged("Unit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Value() As Double
            Get
                Return Me.ValueField
            End Get
            Set
                If (Me.ValueField.Equals(value) <> true) Then
                    Me.ValueField = value
                    Me.RaisePropertyChanged("Value")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Money", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Money
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CurrencyCodeField As String
        
        Private ValueField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property CurrencyCode() As String
            Get
                Return Me.CurrencyCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CurrencyCodeField, value) <> true) Then
                    Me.CurrencyCodeField = value
                    Me.RaisePropertyChanged("CurrencyCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Value() As Double
            Get
                Return Me.ValueField
            End Get
            Set
                If (Me.ValueField.Equals(value) <> true) Then
                    Me.ValueField = value
                    Me.RaisePropertyChanged("Value")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ShipmentItem", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ShipmentItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private PackageTypeField As String
        
        Private QuantityField As Integer
        
        Private WeightField As RateCalcService.Weight
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CommentsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReferenceField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property PackageType() As String
            Get
                Return Me.PackageTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PackageTypeField, value) <> true) Then
                    Me.PackageTypeField = value
                    Me.RaisePropertyChanged("PackageType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Quantity() As Integer
            Get
                Return Me.QuantityField
            End Get
            Set
                If (Me.QuantityField.Equals(value) <> true) Then
                    Me.QuantityField = value
                    Me.RaisePropertyChanged("Quantity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Weight() As RateCalcService.Weight
            Get
                Return Me.WeightField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WeightField, value) <> true) Then
                    Me.WeightField = value
                    Me.RaisePropertyChanged("Weight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property Comments() As String
            Get
                Return Me.CommentsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CommentsField, value) <> true) Then
                    Me.CommentsField = value
                    Me.RaisePropertyChanged("Comments")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property Reference() As String
            Get
                Return Me.ReferenceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReferenceField, value) <> true) Then
                    Me.ReferenceField = value
                    Me.RaisePropertyChanged("Reference")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Notification", [Namespace]:="http://ws.aramex.net/ShippingAPI/v1/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Notification
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodeField As String
        
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Code() As String
            Get
                Return Me.CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodeField, value) <> true) Then
                    Me.CodeField = value
                    Me.RaisePropertyChanged("Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", ConfigurationName:="RateCalcService.Service_1_0")>  _
    Public Interface Service_1_0
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CalculateRate", ReplyAction:="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CalculateRateResponse")>  _
        Function CalculateRate(ByVal request As RateCalcService.RateCalculatorRequest) As RateCalcService.RateCalculatorResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RateCalculatorRequest", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class RateCalculatorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public ClientInfo As RateCalcService.ClientInfo
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Transaction As RateCalcService.Transaction
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=2)>  _
        Public OriginAddress As RateCalcService.Address
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=3)>  _
        Public DestinationAddress As RateCalcService.Address
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=4)>  _
        Public ShipmentDetails As RateCalcService.ShipmentDetails
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClientInfo As RateCalcService.ClientInfo, ByVal Transaction As RateCalcService.Transaction, ByVal OriginAddress As RateCalcService.Address, ByVal DestinationAddress As RateCalcService.Address, ByVal ShipmentDetails As RateCalcService.ShipmentDetails)
            MyBase.New
            Me.ClientInfo = ClientInfo
            Me.Transaction = Transaction
            Me.OriginAddress = OriginAddress
            Me.DestinationAddress = DestinationAddress
            Me.ShipmentDetails = ShipmentDetails
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RateCalculatorResponse", WrapperNamespace:="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped:=true)>  _
    Partial Public Class RateCalculatorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=0)>  _
        Public Transaction As RateCalcService.Transaction
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=1)>  _
        Public Notifications() As RateCalcService.Notification
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=2)>  _
        Public HasErrors As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.aramex.net/ShippingAPI/v1/", Order:=3)>  _
        Public TotalAmount As RateCalcService.Money
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Transaction As RateCalcService.Transaction, ByVal Notifications() As RateCalcService.Notification, ByVal HasErrors As Boolean, ByVal TotalAmount As RateCalcService.Money)
            MyBase.New
            Me.Transaction = Transaction
            Me.Notifications = Notifications
            Me.HasErrors = HasErrors
            Me.TotalAmount = TotalAmount
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Service_1_0Channel
        Inherits RateCalcService.Service_1_0, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service_1_0Client
        Inherits System.ServiceModel.ClientBase(Of RateCalcService.Service_1_0)
        Implements RateCalcService.Service_1_0
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CalculateRate(ByVal request As RateCalcService.RateCalculatorRequest) As RateCalcService.RateCalculatorResponse Implements RateCalcService.Service_1_0.CalculateRate
            Return MyBase.Channel.CalculateRate(request)
        End Function
    End Class
End Namespace
