//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationAPIClientCSharp.LocationReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientInfo", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class ClientInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        private string VersionField;
        
        private string AccountNumberField;
        
        private string AccountPinField;
        
        private string AccountEntityField;
        
        private string AccountCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string AccountPin {
            get {
                return this.AccountPinField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountPinField, value) != true)) {
                    this.AccountPinField = value;
                    this.RaisePropertyChanged("AccountPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string AccountEntity {
            get {
                return this.AccountEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountEntityField, value) != true)) {
                    this.AccountEntityField = value;
                    this.RaisePropertyChanged("AccountEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string AccountCountryCode {
            get {
                return this.AccountCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountCountryCodeField, value) != true)) {
                    this.AccountCountryCodeField = value;
                    this.RaisePropertyChanged("AccountCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Reference1Field;
        
        private string Reference2Field;
        
        private string Reference3Field;
        
        private string Reference4Field;
        
        private string Reference5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference1 {
            get {
                return this.Reference1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference1Field, value) != true)) {
                    this.Reference1Field = value;
                    this.RaisePropertyChanged("Reference1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference2 {
            get {
                return this.Reference2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference2Field, value) != true)) {
                    this.Reference2Field = value;
                    this.RaisePropertyChanged("Reference2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference3 {
            get {
                return this.Reference3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference3Field, value) != true)) {
                    this.Reference3Field = value;
                    this.RaisePropertyChanged("Reference3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference4 {
            get {
                return this.Reference4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference4Field, value) != true)) {
                    this.Reference4Field = value;
                    this.RaisePropertyChanged("Reference4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference5 {
            get {
                return this.Reference5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference5Field, value) != true)) {
                    this.Reference5Field = value;
                    this.RaisePropertyChanged("Reference5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Line1Field;
        
        private string Line2Field;
        
        private string Line3Field;
        
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateOrProvinceCodeField;
        
        private string PostCodeField;
        
        private string CountryCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line3 {
            get {
                return this.Line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line3Field, value) != true)) {
                    this.Line3Field = value;
                    this.RaisePropertyChanged("Line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string StateOrProvinceCode {
            get {
                return this.StateOrProvinceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StateOrProvinceCodeField, value) != true)) {
                    this.StateOrProvinceCodeField = value;
                    this.RaisePropertyChanged("StateOrProvinceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Notification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string NameField;
        
        private string IsoCodeField;
        
        private bool StateRequiredField;
        
        private bool PostCodeRequiredField;
        
        private string[] PostCodeRegexField;
        
        private string InternationalCallingNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string IsoCode {
            get {
                return this.IsoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IsoCodeField, value) != true)) {
                    this.IsoCodeField = value;
                    this.RaisePropertyChanged("IsoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool StateRequired {
            get {
                return this.StateRequiredField;
            }
            set {
                if ((this.StateRequiredField.Equals(value) != true)) {
                    this.StateRequiredField = value;
                    this.RaisePropertyChanged("StateRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool PostCodeRequired {
            get {
                return this.PostCodeRequiredField;
            }
            set {
                if ((this.PostCodeRequiredField.Equals(value) != true)) {
                    this.PostCodeRequiredField = value;
                    this.RaisePropertyChanged("PostCodeRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string[] PostCodeRegex {
            get {
                return this.PostCodeRegexField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeRegexField, value) != true)) {
                    this.PostCodeRegexField = value;
                    this.RaisePropertyChanged("PostCodeRegex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string InternationalCallingNumber {
            get {
                return this.InternationalCallingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InternationalCallingNumberField, value) != true)) {
                    this.InternationalCallingNumberField = value;
                    this.RaisePropertyChanged("InternationalCallingNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Office", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Office : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EntityField;
        
        private string EntityDescriptionField;
        
        private string OfficeTypeField;
        
        private LocationAPIClientCSharp.LocationReference.Address AddressField;
        
        private string TelephoneField;
        
        private string WorkingDaysField;
        
        private string WorkingHoursField;
        
        private decimal LongtitudeField;
        
        private decimal LatitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EntityDescription {
            get {
                return this.EntityDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityDescriptionField, value) != true)) {
                    this.EntityDescriptionField = value;
                    this.RaisePropertyChanged("EntityDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OfficeType {
            get {
                return this.OfficeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeTypeField, value) != true)) {
                    this.OfficeTypeField = value;
                    this.RaisePropertyChanged("OfficeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public LocationAPIClientCSharp.LocationReference.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string WorkingDays {
            get {
                return this.WorkingDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkingDaysField, value) != true)) {
                    this.WorkingDaysField = value;
                    this.RaisePropertyChanged("WorkingDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string WorkingHours {
            get {
                return this.WorkingHoursField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkingHoursField, value) != true)) {
                    this.WorkingHoursField = value;
                    this.RaisePropertyChanged("WorkingHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", ConfigurationName="LocationReference.Service_1_0")]
    public interface Service_1_0 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ValidateAddress", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ValidateAddressResponse")]
        LocationAPIClientCSharp.LocationReference.AddressValidationResponse ValidateAddress(LocationAPIClientCSharp.LocationReference.AddressValidationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountries", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountriesResponse")]
        LocationAPIClientCSharp.LocationReference.CountriesFetchingResponse FetchCountries(LocationAPIClientCSharp.LocationReference.CountriesFetchingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountry", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountryResponse")]
        LocationAPIClientCSharp.LocationReference.CountryFetchingResponse FetchCountry(LocationAPIClientCSharp.LocationReference.CountryFetchingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCities", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCitiesResponse")]
        LocationAPIClientCSharp.LocationReference.CitiesFetchingResponse FetchCities(LocationAPIClientCSharp.LocationReference.CitiesFetchingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchOffices", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchOfficesResponse")]
        LocationAPIClientCSharp.LocationReference.OfficesFetchingResponse FetchOffices(LocationAPIClientCSharp.LocationReference.OfficesFetchingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddressValidationRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class AddressValidationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public LocationAPIClientCSharp.LocationReference.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public LocationAPIClientCSharp.LocationReference.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public LocationAPIClientCSharp.LocationReference.Address Address;
        
        public AddressValidationRequest() {
        }
        
        public AddressValidationRequest(LocationAPIClientCSharp.LocationReference.ClientInfo ClientInfo, LocationAPIClientCSharp.LocationReference.Transaction Transaction, LocationAPIClientCSharp.LocationReference.Address Address) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddressValidationResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class AddressValidationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public LocationAPIClientCSharp.LocationReference.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public LocationAPIClientCSharp.LocationReference.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public LocationAPIClientCSharp.LocationReference.Address[] SuggestedAddresses;
        
        public AddressValidationResponse() {
        }
        
        public AddressValidationResponse(LocationAPIClientCSharp.LocationReference.Transaction Transaction, LocationAPIClientCSharp.LocationReference.Notification[] Notifications, bool HasErrors, LocationAPIClientCSharp.LocationReference.Address[] SuggestedAddresses) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.SuggestedAddresses = SuggestedAddresses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountriesFetchingRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CountriesFetchingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public LocationAPIClientCSharp.LocationReference.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public LocationAPIClientCSharp.LocationReference.Transaction Transaction;
        
        public CountriesFetchingRequest() {
        }
        
        public CountriesFetchingRequest(LocationAPIClientCSharp.LocationReference.ClientInfo ClientInfo, LocationAPIClientCSharp.LocationReference.Transaction Transaction) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountriesFetchingResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CountriesFetchingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public LocationAPIClientCSharp.LocationReference.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public LocationAPIClientCSharp.LocationReference.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public LocationAPIClientCSharp.LocationReference.Country[] Countries;
        
        public CountriesFetchingResponse() {
        }
        
        public CountriesFetchingResponse(LocationAPIClientCSharp.LocationReference.Transaction Transaction, LocationAPIClientCSharp.LocationReference.Notification[] Notifications, bool HasErrors, LocationAPIClientCSharp.LocationReference.Country[] Countries) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.Countries = Countries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountryFetchingRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CountryFetchingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public LocationAPIClientCSharp.LocationReference.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public LocationAPIClientCSharp.LocationReference.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public string Code;
        
        public CountryFetchingRequest() {
        }
        
        public CountryFetchingRequest(LocationAPIClientCSharp.LocationReference.ClientInfo ClientInfo, LocationAPIClientCSharp.LocationReference.Transaction Transaction, string Code) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountryFetchingResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CountryFetchingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public LocationAPIClientCSharp.LocationReference.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public LocationAPIClientCSharp.LocationReference.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public LocationAPIClientCSharp.LocationReference.Country Country;
        
        public CountryFetchingResponse() {
        }
        
        public CountryFetchingResponse(LocationAPIClientCSharp.LocationReference.Transaction Transaction, LocationAPIClientCSharp.LocationReference.Notification[] Notifications, bool HasErrors, LocationAPIClientCSharp.LocationReference.Country Country) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.Country = Country;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CitiesFetchingRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CitiesFetchingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public LocationAPIClientCSharp.LocationReference.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public LocationAPIClientCSharp.LocationReference.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public string CountryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public string State;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=4)]
        public string NameStartsWith;
        
        public CitiesFetchingRequest() {
        }
        
        public CitiesFetchingRequest(LocationAPIClientCSharp.LocationReference.ClientInfo ClientInfo, LocationAPIClientCSharp.LocationReference.Transaction Transaction, string CountryCode, string State, string NameStartsWith) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.CountryCode = CountryCode;
            this.State = State;
            this.NameStartsWith = NameStartsWith;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CitiesFetchingResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CitiesFetchingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public LocationAPIClientCSharp.LocationReference.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public LocationAPIClientCSharp.LocationReference.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public string[] Cities;
        
        public CitiesFetchingResponse() {
        }
        
        public CitiesFetchingResponse(LocationAPIClientCSharp.LocationReference.Transaction Transaction, LocationAPIClientCSharp.LocationReference.Notification[] Notifications, bool HasErrors, string[] Cities) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.Cities = Cities;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OfficesFetchingRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class OfficesFetchingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public LocationAPIClientCSharp.LocationReference.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public LocationAPIClientCSharp.LocationReference.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public string CountryCode;
        
        public OfficesFetchingRequest() {
        }
        
        public OfficesFetchingRequest(LocationAPIClientCSharp.LocationReference.ClientInfo ClientInfo, LocationAPIClientCSharp.LocationReference.Transaction Transaction, string CountryCode) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.CountryCode = CountryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OfficesFetchingResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class OfficesFetchingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public LocationAPIClientCSharp.LocationReference.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public LocationAPIClientCSharp.LocationReference.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public LocationAPIClientCSharp.LocationReference.Office[] Offices;
        
        public OfficesFetchingResponse() {
        }
        
        public OfficesFetchingResponse(LocationAPIClientCSharp.LocationReference.Transaction Transaction, LocationAPIClientCSharp.LocationReference.Notification[] Notifications, bool HasErrors, LocationAPIClientCSharp.LocationReference.Office[] Offices) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.Offices = Offices;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service_1_0Channel : LocationAPIClientCSharp.LocationReference.Service_1_0, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_1_0Client : System.ServiceModel.ClientBase<LocationAPIClientCSharp.LocationReference.Service_1_0>, LocationAPIClientCSharp.LocationReference.Service_1_0 {
        
        public Service_1_0Client() {
        }
        
        public Service_1_0Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_1_0Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_1_0Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_1_0Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LocationAPIClientCSharp.LocationReference.AddressValidationResponse ValidateAddress(LocationAPIClientCSharp.LocationReference.AddressValidationRequest request) {
            return base.Channel.ValidateAddress(request);
        }
        
        public LocationAPIClientCSharp.LocationReference.CountriesFetchingResponse FetchCountries(LocationAPIClientCSharp.LocationReference.CountriesFetchingRequest request) {
            return base.Channel.FetchCountries(request);
        }
        
        public LocationAPIClientCSharp.LocationReference.CountryFetchingResponse FetchCountry(LocationAPIClientCSharp.LocationReference.CountryFetchingRequest request) {
            return base.Channel.FetchCountry(request);
        }
        
        public LocationAPIClientCSharp.LocationReference.CitiesFetchingResponse FetchCities(LocationAPIClientCSharp.LocationReference.CitiesFetchingRequest request) {
            return base.Channel.FetchCities(request);
        }
        
        public LocationAPIClientCSharp.LocationReference.OfficesFetchingResponse FetchOffices(LocationAPIClientCSharp.LocationReference.OfficesFetchingRequest request) {
            return base.Channel.FetchOffices(request);
        }
    }
}
